{
    "name": "Odoo MCP Control Plane",
    "summary": "Secure policy, approval, and audit layer for external MCP servers",
    "version": "19.0.1.0.0",
    "category": "Technical",
    "website": "https://github.com/oduist/odu_mcp",
    "author": "Odoo MCP Contributors",
    "license": "LGPL-3",
    "depends": ["base", "mail", "web"],
    "data": [
        "security/mcp_security.xml",
        "security/ir.model.access.csv",
        "views/profile_views.xml",
        "views/credential_views.xml",
        "views/approval_views.xml",
        "views/audit_views.xml",
        "views/res_config_settings_views.xml",
        "views/menu_views.xml",
    ],
    "application": False,
    "installable": True,
}
